apiVersion: v1
kind: Service
metadata:
  name: backend-service  #the name that the frontend will use to access the backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  
      targetPort: 5000
  type: ClusterIP  #ensures it's only accessible within the cluster
